In [2]:
import pandas as pd 
import numpy as np
import sklearn as sk 

In [3]:
data = pd.read_csv("toy_ds.csv")
print(data.head(), '\n \n ', data.describe())

  Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7   
 
              Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000  

In [4]:
print(data["Sex"].unique())

['M' 'F' 'I']


In [5]:
data.loc[data["Sex"]=='M' , "Sex" ] = 0
data.loc[data["Sex"]=='F' , "Sex" ] = 1
data.loc[data["Sex"]=='I' , "Sex" ] = 2

In [6]:
data["AgeCategory"] = 0
data.loc[data['Rings'] <9, "AgeCategory"] = 1
data.loc[(data['Rings'] >= 9) & (data['Rings'] <= 10), "AgeCategory"] = 2
data.loc[data['Rings'] >10, "AgeCategory" ] = 3
print(data.groupby('AgeCategory').size(), '\n',
sum(data.groupby('AgeCategory').size()))

AgeCategory
1    1407
2    1323
3    1447
dtype: int64 
 4177


In [7]:
data.groupby('AgeCategory').describe()

Diameter       Height       Length        Rings  \
AgeCategory                                                             
1           count  1407.000000  1407.000000  1407.000000  1407.000000   
            mean      0.321276     0.106596     0.420991     6.884151   
            std       0.090292     0.041830     0.111375     1.216914   
            min       0.055000     0.000000     0.075000     1.000000   
            25%       0.260000     0.085000     0.350000     6.000000   
            50%       0.325000     0.105000     0.430000     7.000000   
            75%       0.385000     0.125000     0.500000     8.000000   
            max       0.565000     1.130000     0.720000     8.000000   
2           count  1323.000000  1323.000000  1323.000000  1323.000000   
            mean      0.436754     0.148171     0.560170     9.479214   
            std       0.069540     0.029392     0.085249     0.499757   
            min       0.205000     0.015000     0.280000     9.000000   
            25%       0.395000     0.130000     0.515000     9.000000   
            50%       0.450000     0.150000     0.575000     9.000000   
            75%       0.485000     0.165000     0.620000    10.000000   
            max       0.600000     0.515000     0.770000    10.000000   
3           count  1447.000000  1447.000000  1447.000000  1447.000000   
            mean      0.465695     0.163614     0.591068    13.314444   
            std       0.068473     0.029277     0.083205     2.770863   
            min       0.235000     0.060000     0.310000    11.000000   
            25%       0.420000     0.145000     0.535000    11.000000   
            50%       0.475000     0.165000     0.600000    12.000000   
            75%       0.515000     0.185000     0.650000    15.000000   
            max       0.650000     0.250000     0.815000    29.000000   

                   Shell weight  Shucked weight  Viscera weight  Whole weight  
AgeCategory                                                                    
1           count   1407.000000     1407.000000     1407.000000   1407.000000  
            mean       0.121394        0.198199        0.093357      0.432374  
            std        0.080965        0.147031        0.068090      0.306007  
            min        0.001500        0.001000        0.000500      0.002000  
            25%        0.060000        0.082250        0.040000      0.196000  
            50%        0.106500        0.165000        0.078500      0.368500  
            75%        0.169750        0.282250        0.129250      0.597000  
            max        0.470000        0.825500        0.385500      1.710000  
2           count   1323.000000     1323.000000     1323.000000   1323.000000  
            mean       0.258777        0.416345        0.204731      0.927122  
            std        0.101876        0.194768        0.091182      0.396543  
            min        0.040000        0.045500        0.026000      0.124000  
            25%        0.185000        0.271250        0.139000      0.646000  
            50%        0.259000        0.415000        0.199000      0.917500  
            75%        0.322500        0.539250        0.264500      1.184000  
            max        0.655000        1.253000        0.541000      2.381000  
3           count   1447.000000     1447.000000     1447.000000   1447.000000  
            mean       0.334784        0.463986        0.243350      1.124204  
            std        0.130774        0.217678        0.103497      0.458919  
            min        0.040000        0.041500        0.024000      0.120000  
            25%        0.249000        0.299500        0.166000      0.793500  
            50%        0.324500        0.437000        0.234000      1.092000  
            75%        0.410000        0.598000        0.306000      1.410500  
            max        1.005000        1.488000        0.760000      2.825500

In [8]:
data_use = data.drop('Rings',1)
table1 = data_use.groupby('AgeCategory')

In [9]:
# table1['Diameter'].agg([np.mean,np.std])

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn import metrics

In [11]:
X = data_use.drop('AgeCategory', 1)
Y = data_use["AgeCategory"].astype('category')

In [12]:
Y.dtypes

category

In [13]:
#OVR_fit = OneVsRestClassifier(LogisticRegression()).fit(X,Y)
#OVO_fit = OneVsOneClassifier(LogisticRegression()).fit(X,Y)
log_fit = LogisticRegression().fit(X,Y)
print(log_fit)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [14]:
#predict_OVR = OVR_fit.predict(X)
#predict_OVO = OVO_fit.predict(X)
predict_log = log_fit.predict(X)

In [15]:
print(metrics.classification_report(Y,predict_log))
print(metrics.confusion_matrix(Y, predict_log))

             precision    recall  f1-score   support

          1       0.67      0.79      0.73      1407
          2       0.51      0.37      0.43      1323
          3       0.66      0.71      0.68      1447

avg / total       0.62      0.63      0.62      4177

[[1115  231   61]
 [ 361  486  476]
 [ 186  231 1030]]


In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
KNN = KNeighborsClassifier()
KNN.fit(X,Y)
predict_KNN = KNN.predict(X)

In [18]:
print(metrics.classification_report(Y,predict_KNN))
print(metrics.confusion_matrix(Y, predict_KNN))

             precision    recall  f1-score   support

          1       0.78      0.85      0.81      1407
          2       0.64      0.66      0.65      1323
          3       0.80      0.71      0.76      1447

avg / total       0.74      0.74      0.74      4177

[[1197  180   30]
 [ 226  872  225]
 [ 111  303 1033]]


In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
RF = RandomForestClassifier(random_state=1)
RF.fit(X,Y)
predict_RF = RF.predict(X)

In [21]:
print(metrics.classification_report(Y,predict_RF))
print(metrics.confusion_matrix(Y, predict_RF))

             precision    recall  f1-score   support

          1       0.97      1.00      0.99      1407
          2       0.98      0.97      0.98      1323
          3       0.99      0.98      0.98      1447

avg / total       0.98      0.98      0.98      4177

[[1402    3    2]
 [  26 1285   12]
 [  10   21 1416]]


In [22]:
from sklearn.ensemble import VotingClassifier

In [23]:
eclf1 = VotingClassifier(estimators = [('lr', log_fit), ('rf', RF), ('knn', KNN)], voting = 'hard')
eclf2 = VotingClassifier(estimators = [('lr', log_fit), ('rf', RF), ('knn', KNN)], voting = 'soft')

eclf1.fit(X,Y)
eclf2.fit(X,Y)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('rf', RandomF...owski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'))],
         n_jobs=1, voting='soft', weights=None)

In [24]:
eclf1_predict = eclf1.predict(X)
eclf2_predict = eclf2.predict(X)

print(metrics.classification_report(Y,eclf1_predict))
print(metrics.confusion_matrix(Y, eclf1_predict))

print(metrics.classification_report(Y,eclf2_predict))
print(metrics.confusion_matrix(Y, eclf2_predict))

             precision    recall  f1-score   support

          1       0.80      0.93      0.86      1407
          2       0.83      0.74      0.78      1323
          3       0.86      0.82      0.84      1447

avg / total       0.83      0.83      0.83      4177

[[1303   83   21]
 [ 178  973  172]
 [ 151  110 1186]]
             precision    recall  f1-score   support

          1       0.90      0.94      0.92      1407
          2       0.91      0.84      0.87      1323
          3       0.91      0.93      0.92      1447

avg / total       0.90      0.90      0.90      4177

[[1316   60   31]
 [ 101 1115  107]
 [  51   53 1343]]


In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
all_alg = {log_fit, RF, KNN, eclf1, eclf2}
scores = {}
score_mean = {}
score_sd = {}
for alg in all_alg:
    scores[alg] = cross_val_score(alg, X, Y, cv = 10);
    score_mean[alg] = scores[alg].mean()
    score_sd[alg] = scores[alg].std()

In [27]:
print("Cross Validation Statistics \n")
for alg in all_alg:
    print("Mean: %0.4f Standard Deviation: %0.4f " % (scores[alg].mean(), scores[alg].std()))

Cross Validation Statistics 

Mean: 0.6220 Standard Deviation: 0.0342 
Mean: 0.6134 Standard Deviation: 0.0193 
Mean: 0.6411 Standard Deviation: 0.0260 
Mean: 0.6148 Standard Deviation: 0.0291 
Mean: 0.6294 Standard Deviation: 0.0233 


In [28]:
from sklearn.decomposition import PCA 

In [29]:
pca_data =  data_use.drop(['Sex', 'AgeCategory'],1)
pca_data.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  
0         0.150  
1         0.070  
2         0.210  
3         0.155  
4         0.055

In [30]:
pca1 = PCA(n_components=7)
pca1.fit(pca_data)

PCA(copy=True, iterated_power='auto', n_components=7, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [31]:
pca_score = pca1.explained_variance_ratio_
print(pca_score)

[  9.74100729e-01   1.14183886e-02   8.37567021e-03   3.03865180e-03
   1.41047670e-03   1.22936128e-03   4.26722250e-04]


In [32]:
pca1_comp = PCA(n_components=1)
pca_data1 = pca1_comp.fit_transform(pca_data)
pca_data1

array([[-0.37297053],
       [-0.72693017],
       [-0.17700541],
       ..., 
       [ 0.41895149],
       [ 0.34791783],
       [ 1.31843776]])

In [33]:
logistic = LogisticRegression(random_state=1)
RF2 = RandomForestClassifier(random_state=1)
KNN2 = KNeighborsClassifier()
ensemble1 = VotingClassifier(estimators = [('lr', logistic), ('rf', RF2), ('knn', KNN2)], voting = 'hard')
ensemble2 = VotingClassifier(estimators = [('lr', logistic), ('rf', RF2), ('knn', KNN2)], voting = 'soft')

alg_total2 = {logistic, RF2, KNN2, ensemble1, ensemble2}
names = {"Logistic Regression", "Random Forest" ,"KNN", "Ensemble Hard", "Ensemble Soft"}

In [34]:
for alg2 in alg_total2:
    alg2.fit(pca_data1, Y)
    temp_predict = alg2.predict(pca_data1)
    print(metrics.classification_report(Y,temp_predict))
    print(metrics.confusion_matrix(Y, temp_predict))

             precision    recall  f1-score   support

          1       0.69      0.95      0.80      1407
          2       0.91      0.56      0.69      1323
          3       0.78      0.78      0.78      1447

avg / total       0.79      0.77      0.76      4177

[[1335   19   53]
 [ 323  740  260]
 [ 268   56 1123]]
             precision    recall  f1-score   support

          1       0.83      0.91      0.87      1407
          2       0.89      0.74      0.81      1323
          3       0.83      0.87      0.85      1447

avg / total       0.85      0.84      0.84      4177

[[1280   51   76]
 [ 154  982  187]
 [ 110   73 1264]]
             precision    recall  f1-score   support

          1       0.61      0.83      0.70      1407
          2       0.36      0.06      0.10      1323
          3       0.51      0.73      0.60      1447

avg / total       0.50      0.55      0.48      4177

[[1162   54  191]
 [ 423   77  823]
 [ 305   80 1062]]
             precision    recal

In [35]:
scores_pca = {}
score_mean_pca = {}
score_sd_pca = {}
for alg in alg_total2:
    scores_pca[alg] = cross_val_score(alg, pca_data1, Y, cv = 5);
    score_mean_pca[alg] = scores_pca[alg].mean()
    score_sd_pca[alg] = scores_pca[alg].std()

In [36]:
print("Cross Validation Statistics \n")
for alg in alg_total2:
    print("Mean: %0.4f Standard Deviation: %0.4f " % (scores_pca[alg].mean(), scores_pca[alg].std()))

Cross Validation Statistics 

Mean: 0.5265 Standard Deviation: 0.0169 
Mean: 0.5121 Standard Deviation: 0.0191 
Mean: 0.5511 Standard Deviation: 0.0290 
Mean: 0.5291 Standard Deviation: 0.0142 
Mean: 0.4798 Standard Deviation: 0.0160 


In [37]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [38]:
lda = LinearDiscriminantAnalysis()
lda.fit(X,Y)
lda_predict = lda.predict(X)
print(metrics.classification_report(Y,temp_predict))
print(metrics.confusion_matrix(Y, temp_predict))
cross_val_score(lda,X,Y, cv = 5).mean()


             precision    recall  f1-score   support

          1       0.94      0.98      0.96      1407
          2       0.94      0.94      0.94      1323
          3       0.96      0.93      0.95      1447

avg / total       0.95      0.95      0.95      4177

[[1376   15   16]
 [  46 1243   34]
 [  43   62 1342]]


0.64136697801632492

In [39]:
from sklearn.neural_network import MLPClassifier

In [40]:
clf1 = MLPClassifier()
clf1.fit(X,Y)
clf1_predict = clf1.predict(X)
print(metrics.classification_report(Y,temp_predict))
print(metrics.confusion_matrix(Y, temp_predict))
print(cross_val_score(clf1, X,Y,cv= 5).mean())

             precision    recall  f1-score   support

          1       0.94      0.98      0.96      1407
          2       0.94      0.94      0.94      1323
          3       0.96      0.93      0.95      1447

avg / total       0.95      0.95      0.95      4177

[[1376   15   16]
 [  46 1243   34]
 [  43   62 1342]]
0.643056800712
